### ISSUE TITLE
Identify web api endpoints needed to support 1st milestone

### ISSUE THREAD

**Issue by AarjavP** [AarjavP/Brick#5]
- [ ] player auth (which player is communicating with the server?)
- [ ] Game lobby info
- [ ] Board view from player's POV
- [ ] Possible moves
- [ ] Submit player move
- [ ] more detailed info on power ups or pieces
- [ ] "game scoreboard"
